function [fitresult, gof] = createFit_wall(X_wall, Y_wall)
%CREATEFIT(X_WALL,Y_WALL)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: X_wall
%      Y Output: Y_wall
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Jan-2024 17:33:07


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( X_wall, Y_wall );

% Set up fittype and options.
ft = 'linearinterp';
opts = fitoptions( 'Method', 'LinearInterpolant' );
opts.ExtrapolationMethod = 'linear';
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );


