function [fitresult, gof] = createFit(X, P)
%CREATEFIT(X,P)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: X
%      Y Output: P
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Jan-2024 17:20:03


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( X, P );

% Set up fittype and options.
ft = 'linearinterp';
opts = fitoptions( 'Method', 'LinearInterpolant' );
opts.ExtrapolationMethod = 'linear';
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );


